### ISSUE TITLE
SDK test case fixes for Arbitrum hackathon

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2-sdk#16]

**Comment by codenamejason** [comment]
Briefly spoke with @0xKurt about setting up our tests via Hardhat and Jest - WDYT @thelostone-mc ?

**Comment by 0xKurt** [comment]
Reason:
The current testcases are useless, as we noticed during SeaGrants development. A better way could be to test against a local blockchain, which is possible using hardhat (even if we don't use this repo to develop contracts itself)
